version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes1.cs799-serverless-pg0.utah.cloudlab.us:31112
functions:
  valve-product-photos-4-success:
    lang: node10-express
    handler: ./product-photos-4-success
    image: dsirone/valve-product-photos-4-success:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
