version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  product-photos-4-success:
    lang: node10-express
    handler: ./product-photos-4-success
    image: innocentjr1995/product-photos-4-success:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    annotations:
      com.openfaas.profile: test
    
