version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes1.cs799-serverless-pg0.utah.cloudlab.us:31112
functions:
  product-photos-2-message:
    lang: node10-express
    handler: ./product-photos-2-message
    image: dsirone/product-photos-2-message:latest
