version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  product-photos-2-message:
    lang: node10-express
    handler: ./product-photos-2-message
    image: innocentjr1995/product-photos-2-message:latest
