version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  trapeze-product-photos-1-microbench:
    lang: node10-express
    handler: ./product-photos-1-microbench
    image: innocentjr1995/trapeze-product-photos-1-microbench:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    annotations:
      com.openfaas.profile: test
