version: 1.0
provider:
  name: openfaas
  gateway: http://node4.netes1.cs799-serverless-pg0.utah.cloudlab.us:31112
functions:
  product-catalog-api:
    lang: node10-express
    handler: ./product-catalog-api
    image: dsirone/product-catalog-api:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_CATEGORY_NAME: 'productCategory'
      TABLE_PRODUCT_CATALOG_NAME: 'productCatalog'
      TABLE_PRODUCT_PRICE_NAME: 'productPrice'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
